"""add_invoice_comments

Revision ID: fbbc8bbaf61a
Revises: 002
Create Date: 2026-05-16 01:55:26.860416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbbc8bbaf61a'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('invoice_embeddings')
    op.alter_column('accounting_firms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('accounting_firms_slug_key', 'accounting_firms', type_='unique')
    op.drop_index('ix_accounting_firms_slug', table_name='accounting_firms')
    op.create_index(op.f('ix_accounting_firms_slug'), 'accounting_firms', ['slug'], unique=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('companies', 'business_type',
               existing_type=postgresql.ENUM('manufacturing', 'it', 'services', 'trading', 'other', name='businesstype'),
               nullable=False,
               existing_server_default=sa.text("'other'::businesstype"))
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('companies_slug_key', 'companies', type_='unique')
    op.drop_index('ix_companies_slug', table_name='companies')
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.alter_column('extracted_transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'INR'::character varying"))
    op.alter_column('extracted_transactions', 'line_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('extracted_transactions', 'corrected_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('extracted_transactions', 'is_corrected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('invoices', 'invoice_type',
               existing_type=postgresql.ENUM('purchase', 'sales', 'payment', 'salary_register', 'bank_statement', 'ledger', name='invoicetype'),
               nullable=False,
               existing_server_default=sa.text("'purchase'::invoicetype"))
    op.alter_column('invoices', 'extraction_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('invoices', 'confidence_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('invoices', 'conflicts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('pending', 'under_review', 'needs_correction', 'accepted', 'rejected', name='transactionstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::transactionstatus"))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('payment_heads', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('payment_sub_heads', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('reports', sa.Column('report_type', sa.Enum('mis', 'balance_sheet', 'profit_loss', 'cash_flow', 'gst_summary', 'other', name='reporttype'), nullable=False))
    op.add_column('reports', sa.Column('file_url', sa.String(length=1000), nullable=False))
    op.alter_column('reports', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reports', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('reports', 'period_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('reports', 'period_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint('reports_firm_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'firm_id')
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'file_path')
    op.drop_column('reports', 'is_published')
    op.drop_column('reports', 'type')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('reports', sa.Column('type', postgresql.ENUM('mis', 'balance_sheet', 'profit_loss', 'cash_flow', 'gst_summary', 'custom', name='reporttype'), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('firm_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('reports_firm_id_fkey', 'reports', 'accounting_firms', ['firm_id'], ['id'])
    op.alter_column('reports', 'period_end',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reports', 'period_start',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reports', 'file_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('reports', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('reports', 'file_url')
    op.drop_column('reports', 'report_type')
    op.alter_column('payment_sub_heads', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('payment_heads', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notifications', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('pending', 'under_review', 'needs_correction', 'accepted', 'rejected', name='transactionstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::transactionstatus"))
    op.alter_column('invoices', 'conflicts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('invoices', 'confidence_scores',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('invoices', 'extraction_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('invoices', 'invoice_type',
               existing_type=postgresql.ENUM('purchase', 'sales', 'payment', 'salary_register', 'bank_statement', 'ledger', name='invoicetype'),
               nullable=True,
               existing_server_default=sa.text("'purchase'::invoicetype"))
    op.alter_column('extracted_transactions', 'is_corrected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('extracted_transactions', 'corrected_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('extracted_transactions', 'line_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('extracted_transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'INR'::character varying"))
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.create_index('ix_companies_slug', 'companies', ['slug'], unique=False)
    op.create_unique_constraint('companies_slug_key', 'companies', ['slug'])
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('companies', 'business_type',
               existing_type=postgresql.ENUM('manufacturing', 'it', 'services', 'trading', 'other', name='businesstype'),
               nullable=True,
               existing_server_default=sa.text("'other'::businesstype"))
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_accounting_firms_slug'), table_name='accounting_firms')
    op.create_index('ix_accounting_firms_slug', 'accounting_firms', ['slug'], unique=False)
    op.create_unique_constraint('accounting_firms_slug_key', 'accounting_firms', ['slug'])
    op.alter_column('accounting_firms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_table('invoice_embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='invoice_embeddings_company_id_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoice_embeddings_invoice_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoice_embeddings_pkey'),
    sa.UniqueConstraint('invoice_id', name='invoice_embeddings_invoice_id_key')
    )
    op.drop_table('invoice_comments')
    # ### end Alembic commands ###
