export async function exportAuditReport(apiClient, user) {
  const res = await apiClient.get("/invoices?status=accepted&limit=500");
  const invoices = res.data;
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });

  function fmtAmount(v) {
    if (v == null) return "—";
    return "₹" + Number(v).toLocaleString("en-IN");
  }
  function trustColor(s) {
    if (s >= 85) return "#059669";
    if (s >= 60) return "#d97706";
    return "#e11d48";
  }
  function trustLabel(s) {
    if (s >= 85) return "Auto-Approved";
    if (s >= 60) return "Reviewed";
    return "Manual";
  }

  const rows = invoices.map((inv, i) => {
    const tx = inv.transaction || {};
    const score = inv.trust_score ?? 0;
    return `
      <tr style="border-bottom:1px solid #f1f5f9;${i % 2 === 0 ? "" : "background:#f8fafc"}">
        <td style="padding:10px 12px;font-size:12px;color:#374151;max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="${inv.file_name}">${inv.file_name}</td>
        <td style="padding:10px 12px;font-size:12px;color:#374151">${tx.vendor_name || "—"}</td>
        <td style="padding:10px 12px;font-size:12px;color:#374151;font-family:monospace">${tx.invoice_number || "—"}</td>
        <td style="padding:10px 12px;font-size:12px;color:#374151">${tx.invoice_date || "—"}</td>
        <td style="padding:10px 12px;font-size:12px;color:#374151;text-align:right;font-family:monospace">${fmtAmount(tx.total_amount)}</td>
        <td style="padding:10px 12px;font-size:12px;color:#374151;text-align:right;font-family:monospace">${fmtAmount(tx.tax_amount)}</td>
        <td style="padding:10px 12px;text-align:center">
          <span style="display:inline-flex;align-items:center;gap:4px;padding:3px 10px;border-radius:99px;font-size:11px;font-weight:600;color:${trustColor(score)};background:${trustColor(score)}18">
            ${score}/100 · ${trustLabel(score)}
          </span>
        </td>
        <td style="padding:10px 12px;font-size:11px;color:#94a3b8">${new Date(inv.created_at).toLocaleDateString("en-IN")}</td>
      </tr>`;
  }).join("");

  const totalAmount = invoices.reduce((s, i) => s + (Number(i.transaction?.total_amount) || 0), 0);
  const totalTax = invoices.reduce((s, i) => s + (Number(i.transaction?.tax_amount) || 0), 0);
  const avgScore = invoices.length > 0
    ? Math.round(invoices.reduce((s, i) => s + (i.trust_score || 0), 0) / invoices.length)
    : 0;
  const autoApproved = invoices.filter(i => (i.trust_score ?? 0) >= 85).length;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>FinBridge Audit Report — ${dateStr}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', -apple-system, sans-serif; color: #1e293b; background: #fff; padding: 40px; }
  @media print {
    body { padding: 20px; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
  <!-- Header -->
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;padding-bottom:24px;border-bottom:2px solid #e2e8f0">
    <div>
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
        <div style="width:40px;height:40px;background:#4f46e5;border-radius:10px;display:flex;align-items:center;justify-content:center">
          <span style="color:white;font-weight:800;font-size:14px">FB</span>
        </div>
        <div>
          <p style="font-size:18px;font-weight:700;color:#0f172a">FinBridge</p>
          <p style="font-size:11px;color:#94a3b8">Financial Intelligence Platform</p>
        </div>
      </div>
      <h1 style="font-size:22px;font-weight:700;color:#0f172a;margin-top:4px">Invoice Audit Report</h1>
      <p style="font-size:12px;color:#64748b;margin-top:4px">All accepted invoices — verified by Autonomous Verification Pipeline</p>
    </div>
    <div style="text-align:right">
      <p style="font-size:12px;font-weight:600;color:#374151">Generated by</p>
      <p style="font-size:14px;font-weight:700;color:#0f172a">${user?.full_name || "Accountant"}</p>
      <p style="font-size:11px;color:#94a3b8;margin-top:2px">${dateStr} at ${timeStr}</p>
    </div>
  </div>

  <!-- Summary cards -->
  <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:32px">
    ${[
      { label: "Total Invoices", value: invoices.length, color: "#4f46e5" },
      { label: "Total Invoice Value", value: fmtAmount(totalAmount), color: "#0891b2" },
      { label: "Total Tax (Input Credit)", value: fmtAmount(totalTax), color: "#059669" },
      { label: "Avg Trust Score", value: `${avgScore}/100`, color: avgScore >= 85 ? "#059669" : "#d97706" },
    ].map(c => `
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px">
        <p style="font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px">${c.label}</p>
        <p style="font-size:20px;font-weight:700;color:${c.color};font-family:monospace">${c.value}</p>
      </div>`).join("")}
  </div>

  <!-- AI validation summary -->
  <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:16px;margin-bottom:28px;display:flex;align-items:center;gap:12px">
    <div style="width:36px;height:36px;background:#dcfce7;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0">
      <span style="color:#16a34a;font-size:18px">✓</span>
    </div>
    <div>
      <p style="font-size:13px;font-weight:600;color:#15803d">Autonomous Verification Pipeline</p>
      <p style="font-size:12px;color:#16a34a;margin-top:2px">
        ${autoApproved} of ${invoices.length} invoices (${invoices.length > 0 ? Math.round(autoApproved / invoices.length * 100) : 0}%) reached trust score ≥ 85 and were eligible for auto-approval.
        All invoices cross-validated by Groq Vision · PyMuPDF · OCR Consensus Engine.
      </p>
    </div>
  </div>

  <!-- Table -->
  <table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;font-size:13px">
    <thead>
      <tr style="background:#f8fafc;border-bottom:2px solid #e2e8f0">
        <th style="padding:10px 12px;text-align:left;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">Document</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">Vendor</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">Invoice No.</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">Date</th>
        <th style="padding:10px 12px;text-align:right;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">Amount</th>
        <th style="padding:10px 12px;text-align:right;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">Tax</th>
        <th style="padding:10px 12px;text-align:center;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">AI Score</th>
        <th style="padding:10px 12px;text-align:left;font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em">Processed</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
    <tfoot>
      <tr style="background:#f8fafc;border-top:2px solid #e2e8f0;font-weight:700">
        <td colspan="4" style="padding:10px 12px;font-size:12px;color:#374151">Total (${invoices.length} invoices)</td>
        <td style="padding:10px 12px;text-align:right;font-size:12px;color:#0f172a;font-family:monospace">${fmtAmount(totalAmount)}</td>
        <td style="padding:10px 12px;text-align:right;font-size:12px;color:#0f172a;font-family:monospace">${fmtAmount(totalTax)}</td>
        <td colspan="2"></td>
      </tr>
    </tfoot>
  </table>

  <!-- Footer -->
  <div style="margin-top:40px;padding-top:20px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;align-items:center">
    <div>
      <p style="font-size:11px;color:#94a3b8">This report was generated by FinBridge Autonomous Verification Pipeline.</p>
      <p style="font-size:11px;color:#94a3b8;margin-top:2px">All invoices have been cross-validated by Groq Vision AI, PyMuPDF, and OCR Consensus Engine.</p>
    </div>
    <div style="text-align:right">
      <p style="font-size:11px;font-weight:600;color:#374151">Verified & Exported by</p>
      <p style="font-size:13px;font-weight:700;color:#0f172a">${user?.full_name || "Accountant"}</p>
      <div style="width:120px;height:1px;background:#0f172a;margin:6px 0 2px auto"></div>
      <p style="font-size:10px;color:#94a3b8">Digital Signature</p>
    </div>
  </div>

  <button class="no-print" onclick="window.print()" style="position:fixed;bottom:24px;right:24px;background:#4f46e5;color:white;border:none;padding:12px 24px;border-radius:12px;font-size:14px;font-weight:600;cursor:pointer;box-shadow:0 4px 20px rgba(79,70,229,.4)">
    🖨 Print / Save PDF
  </button>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `finbridge-audit-${now.toISOString().slice(0, 10)}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
